/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* Ver referencias aqui http://bitingenieria.com.ar/doc/ifu/IFUniversal_TLB/IDriver.html*/

package feafip.demo;

import com4j.Holder;
import feafip.bi.ClassFactory;
import feafip.bi.IBarcode;
import feafip.bi.ICertificado;
import feafip.bi.IComprobante;
import feafip.bi.IwsPadron;
import feafip.bi.Iwscdc;
import feafip.bi.Iwsfev1;
import feafip.bi.TipoComprobante;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author amiranda
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Obtener CAE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Descargar Constancia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Generar Cod. Barras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Renovar Certificado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Generar Certificado");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Constatacion Comprobantes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Fecha Vencimiento Cert.");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Consulta Comprobantes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgBox(String text){
        JOptionPane.showMessageDialog(this,
                    text,
                    "FEAFIP Demo",
                    JOptionPane.PLAIN_MESSAGE);
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Los nombres de los parametros de las funciones se obtienen en FEAFIP.pdf
        
        //URLs de autenticacion y negocio. Cambiarlas por las de producción al implementarlas en el cliente(abajo)
        String URLWSAA = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms";
          // Producción: https://wsaa.afip.gov.ar/ws/services/LoginCms
        String URLWSW = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
          // Producción: https://servicios1.afip.gov.ar/wsfev1/service.asmx
        double nro;

        int ptoVta = 30; // ATENCION! SI RECIBE UN ERROR DE FECHA O NUMERO DE COMPROBANTE EN ESTA DEMO CAMBIE ESTE VALOR POR OTRO DE 1 A 9999
        TipoComprobante tipoComp = TipoComprobante.tcFacturaB; // Factura A(Ver excel referencias codigos AFIP)
        Format formatter = new SimpleDateFormat("yyyyMMdd");
        String FechaComp = formatter.format(new Date());
         
        Iwsfev1 wsfev1 = ClassFactory.createwsfev1();
        wsfev1.cuit(20939802593.0);  // Cuit del vendedor
        wsfev1.url(URLWSW);
        if (wsfev1.login("certificado.crt", "clave.key", URLWSAA)){
            if (!wsfev1.sfRecuperaLastCMP(ptoVta, tipoComp.comEnumValue())) {
                msgBox(wsfev1.errorDesc());
            } else {
                nro = wsfev1.sfLastCMP() + 1;
                wsfev1.reset();
                wsfev1.agregaFactura(1, 80, 27929007862.0, nro, nro, FechaComp, 121, 0, 100, 0, "", "", "", "PES", 1);
                wsfev1.agregaIVA(5, 100, 21); // Ver Excel de referencias de codigos AFIP
                if (!wsfev1.autorizar(ptoVta, (TipoComprobante)tipoComp)){
                    msgBox(wsfev1.errorDesc());
                } else {
                    if (wsfev1.sfResultado(0).equals("A")) {
                        msgBox("Felicitaciones! Si ve este mensaje instalo correctamente FEAFIP. CAE y Vencimiento: " + wsfev1.sfcae(0) + " " + wsfev1.sfVencimiento(0));
                    } else {
                        msgBox(wsfev1.autorizarRespuestaObs(0));
                    }
                }
            }
        } else {
            msgBox(wsfev1.errorDesc());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IwsPadron padron = ClassFactory.createwsPadron();
        double cuit = 20939802593.0;
        if (padron.descargarConstancia(cuit, "c:\\datos\\constancia.pdf")) {
            msgBox("Constancia descargada con éxito");  
        } else {
            msgBox(padron.errorDesc());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        IBarcode barcode = ClassFactory.createBarcode();
        try {
            barcode.generarCodigo(20939802593.0, 1, 2, "12345678901234", "20180101", "c:\\datos\\barcode.bmp");
            msgBox("Archivo generado con éxito");
        } catch (Exception e){
            msgBox(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ICertificado certificado = ClassFactory.createCertificado();
        // Se puede agregar la ruta en los parametros de archivo.
        if (certificado.cargarInformacionCertificado("certificado.crt", "clave.key")) {
            if (certificado.renovarCertificado("nuevopedido.csr")){
                msgBox ("Archivo generado exitosamente");
            }
            else {
                msgBox (certificado.errorDesc());
            }
        } else {
            msgBox (certificado.errorDesc());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ICertificado certificado = ClassFactory.createCertificado();
        double cuit = 20939802593f; 
        // Se puede agregar la ruta en los parametros de archivo.
        if (certificado.generarNuevoCertificado("Bit Ingeniería", "FEAFIP", cuit, "nuevopedido.csr", "nuevaclave.key")){
            msgBox ("Archivos generados exitosamente");
        }
        else {
            msgBox (certificado.errorDesc());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //URLs de autenticacion y negocio. Cambiarlas por las de producción al implementarlas en el cliente(abajo)
        String URL_WSAA = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms";
        String URL_WSCDC = "https://wswhomo.afip.gov.ar/WSCDC/service.asmx";

        Iwscdc lwscdc = ClassFactory.createwscdc();
        lwscdc.depurar(true); 
        lwscdc.cuit(20939802593.0);
        lwscdc.url(URL_WSCDC);
        if (lwscdc.login("certificado.crt", "clave.key", URL_WSAA)) {
          if (lwscdc.comprobanteConstatar("CAE", 20939802593.0, 140, 1, 1588, "20170517", 1452.73, "67203477090542", "80", "27929007862")){
            msgBox("Comprobante constatado con éxito.");
          }
          else {
            msgBox(lwscdc.errorDesc());
          }
        } else {
          msgBox(lwscdc.errorDesc());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ICertificado certificado = ClassFactory.createCertificado();
        // Se puede agregar la ruta en los parametros de archivo.
        if (certificado.cargarInformacionCertificado("certificado.crt", "clave.key")) {
            msgBox ("La fecha de vencimiento del certificado es: " + certificado.iC_FechaVencimiento());
        } else {
            msgBox (certificado.errorDesc());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //URLs de autenticacion y negocio. Cambiarlas por las de producción al implementarlas en el cliente(abajo)
        String URLWSAA = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms";
        String URLWSW = "https://wswhomo.afip.gov.ar/wsfev1/service.asmx";
        double nro;
        String cae;
        String vencimiento;
        int ptoVta = 30;
        int tipoComp = 1; 
         
        Iwsfev1 wsfev1 = ClassFactory.createwsfev1(); 
        wsfev1.cuit(20939802593.0);
        wsfev1.url(URLWSW);
        if (wsfev1.login("certificado.crt", "clave.key", URLWSAA)){
            // Se obtiene el ultimo numero de comprobante a modo de ejemplo.
            if (wsfev1.sfRecuperaLastCMP(ptoVta, tipoComp)){
                // Las variables CAE y Vencimiento recuperan estos valores.
                //Para obtener el resto de los valores informados a la AFIP se explora wsfev1.CmpConsultarCbte
                IComprobante cbte = ClassFactory.createComprobante();
                if (wsfev1.cmpConsultarEx(tipoComp, ptoVta, wsfev1.sfLastCMP(), cbte)){
                    msgBox(cbte.codAutorizacion()); //Explorar objeto cbte
                } else {
                  msgBox(wsfev1.errorDesc());
                }
            } else {
                msgBox(wsfev1.errorDesc());
            }
        } else {
            msgBox(wsfev1.errorDesc());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
